### ISSUE TITLE
General organization, files/folder's topology & misc.

### ISSUE THREAD

**Issue by Davide-F5-Marincione** [ACSAI-REPO/ACSAI-sheet#1]
Hello,
I'd say we should organize into multiple .tex files, one for each topic, to _then_ reference from a single main .tex file, [something like this](https://github.com/jameslzhu/riscv-card/tree/master/tex).
Each topic should also get its own folder with name equal to the .tex it contains, like: \Topics\Gravitation\gravitation.tex.
The reason to use a folder for each topic is that during compilation a lot of TeX engines produce other files than the single .pdf, wouldn't like to get something like this into a single folder for each .tex, it would be a mess.
![image](https://user-images.githubusercontent.com/76567598/114730064-d14ec400-9d40-11eb-9da0-1af22c0ae9ab.png)

**Comment by Benjamin-Barda** [comment]
Agree 100% 

I will make a folder one for each chapter then ... sould we use the same latex engine ? if yes what do you suggest ?
I beleive since we are gonna merge evrything into a single pdf is better to use same engine/version. 

Since you are more practical with latex i'll leave this decision to you :)

**Comment by Davide-F5-Marincione** [comment]
Don't think the same LaTeX engine matters, I personally use MiKTeX but as long as it is some LaTeX it should work

**Comment by Benjamin-Barda** [comment]
Before Tonight i will have all the folders with the tex projects for each chapter setup

**Comment by Davide-F5-Marincione** [comment]
Hold up, I'm working on a fast pull request right now

**Comment by Benjamin-Barda** [comment]
Nais

**Comment by Franciszek-Ciecholewski** [comment]
Hi guys how can I contribute to your work

**Comment by FreshMedlar** [comment]
I'm in too

**Comment by Benjamin-Barda** [comment]
I have added you as a contributor to the repo. 

I will open a new issue for people to join!!!!!
