### ISSUE TITLE
Document layout choice

### ISSUE THREAD

**Issue by Davide-F5-Marincione** [ACSAI-REPO/ACSAI-sheet#2]
Another problem to tackle is the choice of what layout we want to use, I am fond of the **scrartcl** document class from the[ KOMA-script package](https://www.ctan.org/pkg/koma-script), but of course we should decide all together.

(Sorry if I am opening multiple issues, but this should be how things are handled right? One post per issue)

**Comment by Benjamin-Barda** [comment]
I believe we should have readability as priority since we are gonna use it for the exam. I personally do not know the differences between the different layouts. If you reckon scrartcl allow for nice readable documents then we should go for it.

**Comment by Davide-F5-Marincione** [comment]
I think it should suit us well then, **scrartcl** changes the page layout such that the paper's space is used more efficiently, for example, (the text was generated through **lipsum**):
This is vector.tex with the **article** layout.
[vectorsArticle.pdf](https://github.com/Benjamin-Barda/ACSAI-sheet/files/6312184/vectorsArticle.pdf)

This, on the other hand, is the same file with the **scrartcl** layout.
[vectors.pdf](https://github.com/Benjamin-Barda/ACSAI-sheet/files/6312175/vectors.pdf)

**Comment by Benjamin-Barda** [comment]
then definitely **scrartcl**
